var searchData=
[
  ['sample_20data_20formats_0',['Sample Data Formats',['../md_docs_2output__formats.html#autotoc_md86',1,'']]],
  ['sample_20utilities_1',['Tips for Sample Utilities',['../md_docs_2usage__notes.html#autotoc_md31',1,'']]],
  ['sample_20utilities_20module_2',['Sample Utilities Module',['../md_docs_2sample__utilities.html',1,'']]],
  ['sample_5fsizes_3',['sample_sizes',['../structsra_1_1_runtime_profile.html#aedde93203a79ab67596eff504eb65c5d',1,'sra::RuntimeProfile']]],
  ['samplesizeconfig_4',['SampleSizeConfig',['../structsra_1_1_sample_size_config.html',1,'sra']]],
  ['samplesizeconfig_20structure_5',['SampleSizeConfig Structure',['../md_docs_2sample__utilities.html#autotoc_md65',1,'']]],
  ['save_5freport_6',['save_report',['../namespacesra.html#a30c28129e40ac484ee366235a166a7d9',1,'sra::save_report(const RuntimeProfile&lt; Unit &gt; &amp;runtime_profile, const std::filesystem::path &amp;filename)'],['../namespacesra.html#ab305a93a190ebc48a44de25aefdea35a',1,'sra::save_report(const RuntimeProfile&lt; Unit &gt; &amp;runtime_profile, const std::string &amp;base_filename=&quot;runtime_report&quot;)']]],
  ['save_5freport_20function_7',['save_report Function',['../md_docs_2runtime__reporter.html#autotoc_md52',1,'']]],
  ['save_5freports_8',['save_reports',['../namespacesra.html#a406737570dd13ef8b60ca8b82bbf4424',1,'sra']]],
  ['save_5freports_20function_9',['save_reports Function',['../md_docs_2runtime__reporter.html#autotoc_md53',1,'']]],
  ['save_5fsamples_10',['save_samples',['../namespacesra.html#a966045601b1804ced230cd02a273946b',1,'sra::save_samples(const Container &amp;samples, Serializer &amp;&amp;serializer, const std::filesystem::path &amp;filename)'],['../namespacesra.html#a1d63662a5c567465a06db3609e042cf0',1,'sra::save_samples(const Container &amp;samples, const std::filesystem::path &amp;filename)']]],
  ['save_5fsamples_20function_11',['save_samples Function',['../md_docs_2sample__utilities.html#autotoc_md69',1,'']]],
  ['script_12',['Plot Generation Script',['../md_docs_2plot__generation.html',1,'']]],
  ['script_20usage_13',['Plotting Script Usage',['../index.html#autotoc_md17',1,'']]],
  ['serialize_5fiterable_14',['serialize_iterable',['../namespacesra.html#a459c3fbbea52cbb016220d812df4beb5',1,'sra']]],
  ['serialize_5fiterable_20function_15',['serialize_iterable Function',['../md_docs_2sample__utilities.html#autotoc_md68',1,'']]],
  ['simple_20runtime_20analyzer_16',['Simple Runtime Analyzer',['../index.html',1,'']]],
  ['size_17',['size',['../structsra_1_1_runtime_profile.html#ac10a3d1f08bbd81e0fb0f3ad0515a9a1',1,'sra::RuntimeProfile']]],
  ['sra_18',['sra',['../namespacesra.html',1,'']]],
  ['sra_3a_3achronoduration_19',['ChronoDuration',['../conceptsra_1_1_chrono_duration.html',1,'sra']]],
  ['sra_3a_3adetail_20',['detail',['../namespacesra_1_1detail.html',1,'sra']]],
  ['sra_3a_3adetail_3a_3afillerfunction_21',['FillerFunction',['../conceptsra_1_1detail_1_1_filler_function.html',1,'sra::detail']]],
  ['sra_3a_3adetail_3a_3asampleserializer_22',['SampleSerializer',['../conceptsra_1_1detail_1_1_sample_serializer.html',1,'sra::detail']]],
  ['sra_3a_3adetail_3a_3astreaminsertable_23',['StreamInsertable',['../conceptsra_1_1detail_1_1_stream_insertable.html',1,'sra::detail']]],
  ['sra_3a_3ahassize_24',['HasSize',['../conceptsra_1_1_has_size.html',1,'sra']]],
  ['started_25',['Getting Started',['../index.html#autotoc_md13',1,'']]],
  ['structure_26',['Structure',['../md_docs_2runtime__analyzer.html#autotoc_md40',1,'RuntimeProfile Structure'],['../md_docs_2sample__utilities.html#autotoc_md65',1,'SampleSizeConfig Structure']]]
];
